FORMAT: 1A
HOST: http://www.wantoto.com

# 台大醫院行動醫療資訊系統API
台大醫院行動醫療資訊系統API。
版本 1.0
# 所有API [/{?UserID,SessionKey}]
所有API都須檢查Session Key是否過期，過期則回傳 401
## 所有API[GET]
+ Parameters
    + UserID (string) ... 使用者帳號
    + SessionKey (string) ... 使用者登入 Session Key

+ Response 401 (application/json)

        {
            "error": "unauthorized"
        }

# Group 病患清單
病患清單相關API
## 列出所有病患 [/patients/{?UserID,SessionKey}]
### 列出所有病患 [GET]
+ Parameters

    + UserID (string) ... 使用者帳號

+ Response 200 (application/json)

        [
            {
                "patient_name" = "王小明" 
            }
        ]

